// Runs Expansion's agentic layer over every open, deterministically-raised
// Opportunity - see computeHealthScores.ts for the equivalent Health
// pattern this mirrors. Never touches the Opportunity row itself (that
// stays the free, always-on baseline, generated by
// prisma/generate-opportunities.ts); the richer review is stored as its own
// AgentAction, shown alongside the original opportunity on the Expansion
// page.
import { prisma } from "@/lib/prisma";
import { computeExpansionReview } from "./agenticLayer";
import { upsertProposedAgentAction } from "@/lib/agentActions";

const TYPE_LABELS: Record<string, string> = {
  price_increase: "Price increase",
  cross_sell: "Cross-sell",
  upsell: "Upsell",
  consumption_growth: "Consumption growth",
};

export async function computeExpansionActionsForWorkspace(workspaceId: string, apiKey: string): Promise<void> {
  const opportunities = await prisma.opportunity.findMany({
    where: { stage: "open", customer: { workspaceId } },
    include: {
      customer: {
        include: {
          interactions: true,
          healthSnapshots: { orderBy: { computedAt: "desc" }, take: 1 },
        },
      },
    },
  });

  console.log(`Expansion agentic layer: reviewing ${opportunities.length} open opportunit${opportunities.length === 1 ? "y" : "ies"}.`);

  for (const o of opportunities) {
    const snap = o.customer.healthSnapshots[0] ?? null;

    const result = await computeExpansionReview(
      o.customer.name,
      o.type,
      Number(o.estimatedArr),
      o.reasoning,
      snap?.tierLabel ?? null,
      snap?.narrative ?? null,
      o.customer.interactions,
      apiKey
    );

    await upsertProposedAgentAction({
      workspaceId,
      customerId: o.customerId,
      subjectId: o.id,
      area: "expansion",
      actionType: "expansion_review",
      headline: `${TYPE_LABELS[o.type] ?? o.type}${result.shouldRaise ? "" : " - reconsider timing"}`,
      reasoning: result.reasoning,
      suggestedNextStep: result.cautionFlag,
      impactArr: o.estimatedArr,
      confidenceLevel: result.confidenceLevel,
      metadata: { shouldRaise: result.shouldRaise, cautionFlag: result.cautionFlag },
    });
    console.log(`  ${o.customer.name} (${o.type}): shouldRaise=${result.shouldRaise}.`);
  }
}
